version: "3.3"
services:
  api:
    build: .
    restart: always
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - apinetwork
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - "./data/db"
    ports:
      - 27017:27017
    user: mongodb
    command: mongod --noauth
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge
